export const legacyProjects = [
  {
    id: "finance-meta-global",
    title: "FinanceMeta Global evidence workspace",
    description: "The public registry for finance, economics, quantitative research, operating standards, program gates, and inspectable project evidence.",
    status: "Verified repository",
    domain: "Research infrastructure",
    tags: ["economics", "registry", "open methods"],
    href: "https://github.com/build-the-future-11/FinanceMeta-Global",
    evidence: "Public repository verified 19 Sep 2026",
  },
  {
    id: "fi-jepa",
    title: "FI-JEPA: learning financial representations",
    description: "A research project exploring joint-embedding predictive architectures for financial sequences, market regimes, and risk. The work investigates useful representations, not guaranteed investment returns.",
    status: "Verified repository",
    domain: "Financial machine learning",
    tags: ["time series", "JEPA", "synthetic baseline"],
    href: "https://github.com/Finance-Meta-Research/FI-JEPA",
    evidence: "Public repository confirmed 20 Sep 2026; research in progress",
  },
  {
    id: "eigen-jepa",
    title: "Eigen-JEPA: market geometry and regimes",
    description: "Explore how covariance structure, eigenspaces, and changing correlations can help describe financial market regimes. A spectral perspective on financial representation learning.",
    status: "Verified repository", domain: "Financial machine learning", tags: ["JEPA", "covariance", "market regimes"],
    href: "https://github.com/Finance-Meta-Research/Eigen-JEPA", evidence: "Public repository confirmed 20 Sep 2026; research in progress",
  },
  {
    id: "eigenfinance",
    title: "EigenFinance: portfolio evaluation",
    description: "Compare equal-weight, inverse-volatility, and shrinkage minimum-variance strategies through walk-forward evaluation, an untouched holdout, and explicit transaction costs.",
    status: "Verified repository", domain: "Portfolio research", tags: ["portfolio", "risk", "walk-forward testing"],
    href: "https://github.com/Finance-Meta-Research/EigenFinance", evidence: "Public repository confirmed 20 Sep 2026; no real-market performance claim",
  },
  {
    id: "lgwm",
    title: "LGWM: Liquidation Graph World Models",
    description: "Study systemic risk as a connected process: how leverage, liquidity, and liquidation links can propagate a shock across institutions and assets. Contact the team to discuss participation.",
    status: "Coming soon", domain: "Systemic risk", tags: ["networks", "liquidity", "stress testing"],
    evidence: "Member project brief coming soon; repository is not public",
  },
  {
    id: "finimmunity",
    title: "Finimmunity: financial resilience and recovery",
    description: "An exploratory financial-immunology framework studying how markets respond to shocks, recover, and develop persistent feedback loops. A research direction, not a demonstrated trading strategy.",
    status: "Coming soon", domain: "Financial resilience", tags: ["market shocks", "recovery", "feedback loops"],
    evidence: "Repository description confirmed 20 Sep 2026; member brief coming soon, repository is private",
  },
  {
    id: "iy-ern",
    title: "Iy-ERN economics research network",
    description: "A public codebase for an economics research and preprint network. Product claims and peer-review status remain bounded by the evidence published in the repository.",
    status: "Verified repository",
    domain: "Research publishing",
    tags: ["economics", "preprints", "publishing"],
    href: "https://github.com/build-the-future-11/Iy-ERN",
    evidence: "Public repository verified 19 Sep 2026",
  },
  {
    id: "portal",
    title: "Finance for All member platform",
    description: "The authenticated working layer for learning, research applications, opportunities, events, chapters, member discovery, saved work, and evidence-aware administration.",
    status: "Verified repository",
    domain: "Community infrastructure",
    tags: ["education", "community", "open source"],
    href: "https://github.com/build-the-future-11/finance4all-global-reach",
    evidence: "Public repository verified 19 Sep 2026",
  },
  {
    id: "inflation-observatory",
    title: "Student cost-of-living observatory",
    description: "A proposed reproducible price-basket study comparing official inflation measures with carefully defined student spending baskets across cities.",
    status: "Proposed",
    domain: "Applied economics",
    tags: ["inflation", "index numbers", "public data"],
    evidence: "Needs a named lead, frozen basket, collection protocol, and review plan",
  },
  {
    id: "digital-payments-access",
    title: "Digital payments, access, and reliability atlas",
    description: "A proposed public-data project separating payment adoption from reliability, consumer safety, merchant experience, and meaningful financial access.",
    status: "Proposed",
    domain: "Financial systems",
    tags: ["UPI", "inclusion", "consumer protection"],
    evidence: "Needs dataset provenance, privacy review, and a causal-claim boundary",
  },
  {
    id: "youth-expectations-panel",
    title: "Youth economic expectations panel",
    description: "A proposed recurring survey of education, work, inflation, and financial confidence with transparent sampling, anonymization, and uncertainty reporting.",
    status: "Proposed",
    domain: "Behavioural economics",
    tags: ["survey", "expectations", "labour market"],
    evidence: "Needs ethics, safeguarding, sampling, and data-retention protocols",
  },
  {
    id: "public-company-lab",
    title: "Open company and sector research lab",
    description: "A proposed research workflow for source-led company analysis, scenario modelling, valuation assumptions, falsifiers, and documented corrections.",
    status: "Proposed",
    domain: "Investment research",
    tags: ["filings", "valuation", "scenario analysis"],
    evidence: "Needs common rubric, conflict policy, reviewers, and publication standard",
  },
];
export const applications = [
  {
    title: "Quantitative Markets & Microstructure Lab",
    description: "Apply for the evidence-led research cohort covering market structure, volatility, forecasting, execution, risk, and robust backtesting.",
    kind: "Application",
    status: "Active intake",
    href: "https://tally.so/r/0Q9qZy?utm_source=member_portal&utm_medium=opportunity",
    verifiedAt: "19 Sep 2026",
  },
  {
    title: "Financial Systems, Access & Policy Lab",
    description: "Apply to research credit, digital payments, inclusion, consumer protection, policy evaluation, fairness, and infrastructure.",
    kind: "Application",
    status: "Active intake",
    href: "https://tally.so/r/lbG8Yk?utm_source=member_portal&utm_medium=opportunity",
    verifiedAt: "19 Sep 2026",
  },
  {
    title: "Finance4All India school & community pilots",
    description: "For schools, educators, student leaders, and community organizations exploring a scoped practical financial-education pilot.",
    kind: "Pilot interest",
    status: "Active intake",
    href: "https://tally.so/r/q4rlKd?utm_source=member_portal&utm_medium=opportunity",
    verifiedAt: "19 Sep 2026",
  },
  {
    title: "Financial Foundations cohort",
    description: "Apply to build finance, economics, markets, systems, and evidence foundations around a concrete final output.",
    kind: "Application",
    status: "Active intake",
    href: "https://tally.so/r/q4rLG9?utm_source=member_portal&utm_medium=opportunity",
    verifiedAt: "19 Sep 2026",
  },
  {
    title: "Start a local chapter",
    description: "Propose a school, university, or city chapter. Public active status follows approval, an operating cadence, and a qualifying output.",
    kind: "Application",
    status: "Active intake",
    href: "https://tally.so/r/XxaB1j?utm_source=member_portal&utm_medium=opportunity",
    verifiedAt: "19 Sep 2026",
  },
  {
    title: "Partners, speakers, and research collaborators",
    description: "For institutions, educators, researchers, speakers, data providers, and bounded program or research collaborations.",
    kind: "Collaboration",
    status: "Interest route",
    href: "https://tally.so/r/2EWxzb?utm_source=member_portal&utm_medium=opportunity",
    verifiedAt: "19 Sep 2026",
  },
];
