export type ProjectStatus = 'Repository available' | 'Proposal' | 'Proposed' | 'Preregistered' | 'Replication' | 'Recruiting' | 'Active' | 'Analysis' | 'Writing' | 'Under Review' | 'Published' | 'Completed' | 'Archived';
export interface ResearchProtocol { hypothesis: string; baseline: string; evaluation: string; reproducibility: string; references: {label:string;url:string}[]; status: 'Draft' | 'Frozen'; frozenAt?: string; artifact?: string }
export interface CurriculumStage { title: string; work: string; deliverable: string }
export interface CohortCurriculum { track: string; workload: string; selection: string; stages: CurriculumStage[]; intakeCall: string }
export interface Lab { slug: string; number: string; title: string; short: string; thesis: string; description: string; themes: string[]; methods: string[]; tools: string[] }
export interface Project { protocol?: ResearchProtocol; advisor?: string; relatedProjects?: string[]; openPositions?: string[]; slug: string; name: string; status: ProjectStatus; statusNote: string; lab: string; question: string; abstract: string; methods: string[]; datasets: string[]; researchers: string[]; timeline: string; repository?: string; paper?: string; publication?: string; cohort?: string; keywords: string[]; results: string; limitations: string; updated: string; evidence: string }
export interface Cohort { curriculum?: CohortCurriculum; slug: string; title: string; lab: string; status: 'Open' | 'Upcoming' | 'Active' | 'Completed'; duration: string; question: string; difficulty: string; background: string; methods: string[]; output: string[]; applicationStatus: string; description: string }
export interface Publication { slug: string; title: string; authors: string[]; date: string; lab?: string; abstract: string; tags: string[]; type: 'Research Note' | 'Working Paper' | 'IyERJ' | 'FinanceDebriefed' | 'Research Paper' | 'Technical Report' | 'Market Study' | 'Replication Study' | 'Dataset' | 'Benchmark'; status: string; body: string; readMinutes: number; question?: string; methods?: string[]; findings?: string; limitations: string; pdf?: string; code?: string; data?: string }
export interface Person { affiliations?: {relationship: string; organization: string}[]; projects?: string[]; slug: string; name: string; role: string; group: 'Leadership' | 'Research Leads' | 'Lab Leads' | 'Researchers' | 'Engineering' | 'Publications / Media' | 'Operations' | 'Advisors' | 'Contributors' | 'Cohort Leads'; bio: string; publicProfile?: string }
export interface Episode { highlights?: string[]; guestSlug?: string; slug: string; title: string; guest: string; guestDescription: string; type: 'Research' | 'Markets' | 'Builders' | 'Next Generation'; date: string; duration: string; summary: string; topics: string[]; mediaUrl: string; transcript?: string; relatedResearch: string[] }
export interface ResearchEvent { mode?: 'Virtual' | 'In-person' | 'Hybrid'; location?: string; startsAt?: string; endsAt?: string; agenda?: string[]; hosts?: string[]; resources?: {label:string;url:string}[]; slug: string; title: string; type: 'Research Seminar' | 'Speaker Session' | 'Workshop' | 'Cohort Demo Day' | 'Competition' | 'Community Event'; date: string; time: string; timezone: string; speaker?: string; description: string; registration?: string; status: 'Upcoming' | 'Past' | 'Cancelled'; recording?: string; relatedPublication?: string }
export interface Resource { slug: string; title: string; type: 'Guide' | 'Template' | 'Code' | 'Visualization' | 'Course' | 'Dataset'; topic: string; description: string; href: string; available: boolean; level?: string; duration?: string; modules?: string[]; prerequisites?: string; outcomes?: string[] }
export interface Program { slug: string; title: string; section: string; summary: string; status: string; sections: { title: string; text: string }[]; action?: string; actionLabel?: string }
export interface Chapter { institution?: string; governance?: string; programs?: string[]; eventSlugs?: string[]; projectSlugs?: string[]; slug: string; name: string; country: string; location: string; lead: string; status: 'Proposed' | 'Active' | 'Paused'; activities: string[]; contact: string }
