import type { Lab, Cohort, Project, Publication, Episode, ResearchEvent, Chapter, Person, Resource } from './models';
import { legacyProjects } from './legacy-catalog';
import editorialExplainers from './editorial-index.json';

export const labs: Lab[] = [
  { slug:'quantitative-finance-asset-pricing', number:'01', title:'Quantitative Finance & Asset Pricing', short:'Quantitative finance', thesis:'Ask what survives the cost of being wrong.', description:'Study the sources of returns, how portfolios take risk, and which apparent anomalies survive a careful attempt to disprove them. The research agenda puts realistic implementation beside statistical evidence.', themes:['Asset pricing','Systematic strategies','Portfolio construction','Factor models','Risk premia','Volatility','Anomalies','Robustness','Transaction costs'], methods:['Walk-forward evaluation','Factor models','Sensitivity analysis'], tools:['Versioned price histories','Point-in-time universe definitions','Cost-aware evaluation'] },
  { slug:'financial-econometrics-causal-inference', number:'02', title:'Financial Econometrics & Causal Inference', short:'Econometrics & causality', thesis:'A convincing explanation needs a credible counterfactual.', description:'Investigate financial and economic relationships through research designs that make identification assumptions visible. Model sophistication cannot rescue an unconvincing comparison.', themes:['Causal inference','Panel data','Event studies','Difference-in-differences','Instrumental variables','Synthetic controls','Financial time series','Model uncertainty','Statistical robustness'], methods:['Event studies','Difference-in-differences','Panel models','Synthetic controls'], tools:['Reproducible notebooks','Design and assumption ledgers','Public economic data'] },
  { slug:'macro-monetary-financial-economics', number:'03', title:'Macro, Monetary & Financial Economics', short:'Macro & monetary economics', thesis:'Understand the economy as it was knowable at the time.', description:'Study inflation, policy, credit, and economic forecasts while respecting release dates and revisions. Distinguish a persuasive retrospective explanation from information a decision-maker could actually have used.', themes:['Inflation','Monetary policy','Labor markets','Interest rates','Yield curves','Credit','Economic forecasting','Financial conditions','Macro-finance'], methods:['Vintage-aware forecasting','Linear models','Rolling evaluation'], tools:['Release calendars','Vintage economic series','Forecast origin ledgers'] },
  { slug:'market-microstructure-financial-systems', number:'04', title:'Market Microstructure & Financial Systems', short:'Markets & financial systems', thesis:'The mechanism matters as much as the model.', description:'Examine how liquidity, execution, market architecture, and payment infrastructure shape outcomes. A price on a screen and an executable trade are different observations.', themes:['Liquidity','Bid/ask spreads','Execution','Price discovery','Order flow','Market impact','Exchanges','Payments','Clearing','Settlement'], methods:['Execution-cost analysis','Stress testing','Network analysis'], tools:['Authorized quote and trade data','Execution assumptions','Payments datasets'] },
  { slug:'corporate-finance-private-markets', number:'05', title:'Corporate Finance & Private Markets', short:'Corporate & private markets', thesis:'Make the assumptions behind a valuation inspectable.', description:'Study how businesses fund investment, allocate capital, and change ownership. Scenario analysis makes the effects of leverage, operating performance, financing costs, and exit assumptions visible.', themes:['Capital structure','Corporate investment','M&A','Private equity','Venture capital','Credit','Valuation','LBOs','Capital allocation'], methods:['Scenario analysis','Sensitivity analysis','Source-led valuation'], tools:['Public company filings','Assumption ledgers','Reproducible financial models'] },
  { slug:'machine-learning-for-finance', number:'06', title:'Machine Learning for Finance', short:'Machine learning for finance', thesis:'When does a model learn structure, and when does it learn the test?', description:'Study when financial machine learning works, why it fails, and whether performance survives changes in time, sectors, and volatility. Begin with strong simple baselines, then ask what a learned representation adds.', themes:['Representation learning','Self-supervised learning','Transformers','Multimodal finance','Financial NLP','Graph learning','Temporal modeling','Uncertainty','Calibration','Distribution shift','Robustness'], methods:['Temporal OOD','Chronological splits','Calibration','Representation learning','Ablation studies'], tools:['Licensed time-series datasets','Versioned experiment configurations','Leakage audits'] },
  { slug:'behavioral-household-finance', number:'07', title:'Behavioral & Household Finance', short:'Behavioral & household finance', thesis:'Financial systems are experienced one decision at a time.', description:'Investigate how people understand risk, use credit, save, and respond to financial information. Research involving participants needs a suitable consent, safeguarding, and privacy process before collection begins.', themes:['Investor behavior','Financial literacy','Household finance','Savings','Credit','Risk perception','Behavioral biases','Financial misinformation'], methods:['Survey design','Uncertainty reporting','Causal inference'], tools:['Anonymized survey instruments','Consent and retention plans','Public household statistics'] },
];

const cohortSeeds = [
  ['realitycheck','RealityCheck',0,'Which reported financial strategies survive rigorous real-world evaluation?','Look for leakage before looking for performance. Investigate look-ahead and survivorship bias, parameter sensitivity, multiple testing, and regime dependence.',['Temporal holdouts','Transaction costs','Sensitivity analysis','Multiple-testing controls'],['RealityCheck Benchmark','Research report','Open evaluation framework','Reproducible experiments'],'Intermediate','Python, basic statistics, and an interest in systematic evaluation.'],
  ['causal-finance','Causal Finance',1,'Which financial and economic relationships remain credible under a defensible causal design?','Start with the assignment mechanism, treatment, comparison group, and identification assumptions. Research design comes before model complexity.',['Event studies','Difference-in-differences','Instrumental variables','Panel models','Synthetic controls'],['Research-design memo','Reproducible analysis','Assumption and robustness ledger'],'Intermediate','Statistics, regression, and willingness to interrogate assumptions.'],
  ['macrocast','MacroCast',2,'How accurately can economic variables be forecast using only information available at the prediction date?','Compare forecasts of inflation, unemployment, production, rates, yield curves, and growth proxies. Every observation needs a release date and a revision policy.',['Vintage-aware forecasting','Linear models','Tree models','Temporal models'],['Release-aware benchmark','Forecast comparison','Data-vintage documentation'],'Intermediate','Time-series fundamentals and Python or R.'],
  ['market-frictions','Market Frictions',3,'How much apparent financial performance disappears under realistic market frictions?','Introduce commissions, spread, slippage, execution delays, liquidity limits, turnover, and market impact progressively. Keep every implementation assumption inspectable.',['Execution-cost analysis','Sensitivity analysis','Liquidity stress tests'],['Cost-sensitivity report','Interactive visualization','Reproducible execution assumptions'],'Intermediate','Basic market mechanics and quantitative reasoning.'],
  ['capitallab','CapitalLab',4,'Which assumptions explain variation in modeled leveraged-buyout returns?','Separate operational improvement from leverage, financing terms, and exit multiples. Explore how rate sensitivity and capital structure change a valuation.',['Scenario analysis','Sensitivity analysis','Source-led valuation'],['Transparent LBO model','Assumption-attribution study','Research note'],'Intermediate','Financial statements, spreadsheet modeling, and basic corporate finance.'],
  ['finml-benchmark','FinML Benchmark',5,'How much financial ML performance survives realistic temporal and distributional evaluation?','Compare linear and logistic models, forests, boosting, MLPs, LSTMs, temporal CNNs, transformers, and representation learners. Freeze evaluation before tuning.',['Chronological splits','Rolling evaluation','Temporal OOD','Calibration','Ablation studies'],['Financial ML benchmark specification','Reproducible comparison suite','Limitations and failure report'],'Advanced','Python, statistical learning, time-series evaluation, and reproducible experiments.'],
] as const;
export const cohorts: Cohort[] = cohortSeeds.map(([slug,title,lab,question,description,methods,output,difficulty,background])=>({slug,title,lab:labs[lab].slug,question,description,methods:[...methods],output:[...output],difficulty,background,status:'Upcoming',duration:'Schedule to be announced',applicationStatus:'Proposed program · intake not announced'}));
export const projects: Project[] = cohorts.map(c=>({slug:c.slug,name:c.title,lab:c.lab,status:'Proposed',statusNote:'Research protocol in planning',question:c.question,abstract:c.description,methods:c.methods,datasets:[],researchers:[],timeline:'A launch date has not been announced.',cohort:c.slug,keywords:labs.find(l=>l.slug===c.lab)!.themes.slice(0,4),results:'No experiments or results have been released for this proposed study.',limitations:'The dataset, lead, final protocol, and review schedule must be agreed before the study begins.',updated:'2026-09-21',evidence:'Research agenda supplied for the 2026 website; these are proposals, not completed studies.'}));
const labByLegacy: Record<string,number> = {'finance-meta-global':5,'fi-jepa':5,'eigen-jepa':5,'eigenfinance':0,'lgwm':3,'finimmunity':3,'iy-ern':1,'portal':6,'inflation-observatory':2,'digital-payments-access':3,'youth-expectations-panel':6,'public-company-lab':4};
projects.push(...legacyProjects.map(p=>({slug:p.id,name:p.title,lab:labs[labByLegacy[p.id]].slug,status:(p.status==='Verified repository'?'Repository available':'Proposed') as Project['status'],statusNote:p.status==='Verified repository'?'Repository available · current activity unverified':'Research direction',question:p.description,abstract:p.description,methods:p.id==='fi-jepa'?['Representation learning','Chronological splits','Ablation studies']:[],datasets:[],researchers:[],timeline:'No public milestone schedule is confirmed.',repository:p.href,keywords:p.tags,results:p.id==='fi-jepa'?'The local evidence package contains a linear representation baseline and three synthetic sanity experiments. The separate public repository contains a neural implementation and benchmark tooling. These are distinct artifacts; no real-market performance claim is established here.':'No findings are claimed in this public project index.',limitations:p.id==='fi-jepa'?'Synthetic sanity checks do not establish market alpha, deployment readiness, or real-data generalization. A public codebase or manuscript is not evidence of independent review.':'Repository availability and project descriptions do not establish completed research or independently verified outcomes.',updated:'2026-09-20',evidence:p.evidence||'Preserved from the existing public project catalog.'})));

const legacyQuestions: Record<string,string> = {
 'finance-meta-global':'How can research questions, methods, and claims stay connected to inspectable evidence?',
 'fi-jepa':'Can self-supervised representations of financial sequences capture useful economic structure without directly optimizing for returns?',
 'eigen-jepa':'What can covariance structure and changing eigenspaces tell us about financial market regimes?',
 'eigenfinance':'How do simple portfolio strategies compare under walk-forward evaluation and explicit transaction costs?',
 'lgwm':'How can leverage, liquidity, and liquidation links propagate a shock through a financial network?',
 'finimmunity':'How do markets respond to shocks, recover, and develop persistent feedback loops?',
 'iy-ern':'How can an economics research network make preprints and review status easier to inspect?',
 'portal':'How can learning, research participation, and community work share a useful member platform?',
 'inflation-observatory':'How do transparent student price baskets compare with official inflation measures?',
 'digital-payments-access':'When does payment adoption translate into reliable, safe, and meaningful financial access?',
 'youth-expectations-panel':'How do young people describe their economic expectations, and what can a careful sample establish?',
 'public-company-lab':'How can source-led company analysis make valuation assumptions and falsifiers explicit?',
};
for (const project of projects) if (legacyQuestions[project.slug]) project.question = legacyQuestions[project.slug];

export const publications: Publication[] = editorialExplainers.map((p,i)=>({slug:p.slug,title:p.title,authors:[],date:p.reviewedAt,lab:labs[[4,2,3,1][i]??1].slug,abstract:p.dek,tags:[['Markets','Explainers'],['Economics','Explainers'],['Financial systems','Explainers'],['Research','Explainers']][i]??['Explainers'],type:'FinanceDebriefed',status:'Available explainer',body:'',readMinutes:p.readMinutes,limitations:'An educational explainer from the existing Finance for All library. It is not an empirical research finding or personalized financial advice. An individual author and original publication date are not recorded; the date shown is the editorial review date.'}));
export const episodes: Episode[] = [];
export const events: ResearchEvent[] = [];
export const chapters: Chapter[] = [];
export const people: Person[] = [];
export const resources: Resource[] = [
  {slug:'research-protocol',title:'Research protocol worksheet',type:'Template',topic:'Reproducibility',description:'Define the question, baseline, data rights, evaluation, and failure condition before running an experiment.',href:'/resources/research-protocol.md',available:true},
  {slug:'claim-checklist',title:'Before you publish a finding',type:'Guide',topic:'Research integrity',description:'A practical checklist for linking a claim to data, methods, uncertainty, and limitations.',href:'/resources/claim-checklist.md',available:true},
  {slug:'market-frictions',title:'The cost of a trade',type:'Visualization',topic:'Market microstructure',description:'Explore how assumed trading costs and turnover affect a hypothetical gross return.',href:'/studio/visualization',available:true},
  {slug:'fi-jepa-code',title:'FI-JEPA research code',type:'Code',topic:'Machine learning',description:'Inspect the public implementation and benchmark tooling. Repository availability is separate from research validation.',href:'https://github.com/Finance-Meta-Research/FI-JEPA',available:true},
  ...publications.map(p=>({slug:p.slug,title:p.title,type:'Guide' as const,topic:p.tags[0],description:p.abstract,href:`/publications/financedebriefed/${p.slug}`,available:true})),
];
export const getLab = (slug: string) => labs.find(l=>l.slug===slug)!;

export const publicationPath = (p: Publication) => `/publications/${({'Research Note':'research-notes','Working Paper':'working-papers','IyERJ':'iyerj','FinanceDebriefed':'financedebriefed'} as const)[p.type]}/${p.slug}`;
