import { useEffect, useState } from 'react';
import { PageHeader, Section, LinkButton } from './components';
import { cohorts } from './content/research';
import { curricula } from './content/curricula';
import { growth, amortize, purchasingPower, bond, portfolioRisk, valuation, scenarioCsv } from './lib/finance-tools';
import type { ScenarioRow } from './lib/finance-tools';
import './features.css';

const models = {
 growth: {title:'Compound growth',fields:['Initial amount','Monthly contribution','Annual effective growth (%)','Years'],defaults:[1000,100,5,10],assumptions:'Growth is constant, compounded monthly at the equivalent effective rate. Contributions arrive at month end. Taxes, fees and market variability are excluded.'},
 loan: {title:'Loan amortization',fields:['Principal','Annual nominal rate (%)','Term in years','Extra monthly payment'],defaults:[100000,6,20,0],assumptions:'Fixed nominal rate, monthly payments and no fees or penalties. Calculations keep full precision; lender rounding conventions may differ.'},
 inflation: {title:'Purchasing power',fields:['Future nominal amount','Annual inflation (%)','Years'],defaults:[1000,3,10],assumptions:'Constant hypothetical annual inflation. Present purchasing power equals the nominal amount divided by the accumulated price-level change.'},
 bond: {title:'Bond price and duration',fields:['Face value','Annual coupon (%)','Annual yield (%)','Whole years to maturity'],defaults:[100,5,6,10],assumptions:'Annual coupon and annual compounding, no default, accrued interest, call option or tax. Modified duration is a local sensitivity, not an exact large-change forecast.'},
 risk: {title:'Diversification',fields:['Weight of asset A (0–1)','Annual volatility A (%)','Annual volatility B (%)','Correlation (−1 to 1)'],defaults:[.5,20,20,0],assumptions:'A two-asset hypothetical portfolio with fixed weights, volatilities and correlation. It estimates volatility, not expected returns or maximum loss.'},
 valuation: {title:'Cash-flow valuation',fields:['Current annual cash flow','Annual cash-flow growth (%)','Annual discount rate (%)','Whole-year horizon'],defaults:[1000,3,8,10],assumptions:'Cash flows grow from the current value and arrive at year end. Finite horizon only: no terminal value, tax adjustments or enterprise-to-equity bridge.'},
} as const;
type ModelKey=keyof typeof models;
const number=(v:number)=>v.toLocaleString('en',{maximumFractionDigits:4});
function download(text:string,name:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function FinanceTools(){
 const [kind,setKind]=useState<ModelKey>('growth'),[values,setValues]=useState<string[]>(models.growth.defaults.map(String)),[message,setMessage]=useState('');
 useEffect(()=>{const params=new URLSearchParams(window.location.search),key=params.get('model');if(key&&Object.hasOwn(models,key)){const m=key as ModelKey;setKind(m);setValues(models[m].defaults.map((v,i)=>params.get(`v${i}`)??String(v)));}},[]);
 const model=models[kind];let rows:ScenarioRow[]=[],summary:[string,number][]=[],error='';
 try{if(values.some(v=>!v.trim()))throw new Error('Enter a value for every assumption.');const [a,b,c,d]=values.map(Number);
 if(kind==='growth'){rows=growth(a,b,c,d);summary=[['Final balance',rows.at(-1)!.balance],['Total contributions',rows.at(-1)!.contributed],['Growth',rows.at(-1)!.interest]];}
 if(kind==='loan'){const r=amortize(a,b,c,d);rows=r.rows;summary=[['Scheduled monthly payment',r.payment],['Months to repay',r.months],['Total interest',r.totalInterest]];}
 if(kind==='inflation')summary=[['Present purchasing power',purchasingPower(a,b,c)]];
 if(kind==='bond'){const r=bond(a,b,c,d);summary=[['Price',r.price],['Macaulay duration (years)',r.duration],['Modified duration',r.modifiedDuration]];}
 if(kind==='risk')summary=[['Portfolio volatility (%)',portfolioRisk(a,b,c,d)]];
 if(kind==='valuation')summary=[['Present value of forecast cash flows',valuation(a,b,c,d)]];
 }catch(e){error=e instanceof Error?e.message:'Check the assumptions.';}
 async function share(){const url=new URL(window.location.href);url.search='';url.searchParams.set('model',kind);values.forEach((v,i)=>url.searchParams.set(`v${i}`,v));window.history.replaceState(null,'',url);try{await navigator.clipboard.writeText(url.href);setMessage('Scenario link copied.');}catch{setMessage('Scenario saved in the address bar. Copy the address to share it.');}}
 return <><PageHeader eyebrow="Open tools / Finance" title="Explore the assumptions." description="Six transparent calculators for learning. Every value is an editable hypothetical assumption; no market feed or personal recommendation is involved."/>
 <div className="feature-panel"><label>Calculator<select value={kind} onChange={e=>{const k=e.target.value as ModelKey;setKind(k);setValues(models[k].defaults.map(String));setMessage('');}}>{Object.entries(models).map(([key,m])=><option key={key} value={key}>{m.title}</option>)}</select></label><div className="feature-inputs">{model.fields.map((f,i)=><label key={`${kind}-${f}`}>{f}<input type="number" step="any" value={values[i]??''} onChange={e=>setValues(old=>old.map((v,j)=>j===i?e.target.value:v))}/></label>)}</div><p>{model.assumptions}</p><p>Monetary inputs must use the same currency. No currency conversion is performed.</p><p role="alert">{error}</p>
 {!error&&<><dl className="feature-results">{summary.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{number(value)}</dd></div>)}</dl><div className="page-actions"><button type="button" className="button secondary" onClick={share}>Copy scenario link</button><button type="button" className="button secondary" onClick={()=>download(JSON.stringify({model:kind,inputs:values.map(Number),assumptions:model.assumptions,results:Object.fromEntries(summary),rows},null,2),'finance-scenario.json','application/json')}>Export assumptions & results</button>{rows.length>0&&<button type="button" className="button secondary" onClick={()=>download(scenarioCsv(rows),'finance-scenario.csv','text/csv')}>Export table CSV</button>}</div></>}
 <button type="button" className="text-button" onClick={()=>{setValues(model.defaults.map(String));setMessage('Inputs reset.');}}>Reset inputs</button><p role="status">{message}</p></div>
 {!error&&rows.length>0&&<Section title="Calculation table"><div className="responsive-table"><table><caption>{kind==='loan'?'Monthly repayment schedule':'Annual balance and contributions'}</caption><thead><tr><th scope="col">{kind==='loan'?'Month':'Year'}</th><th scope="col">Balance</th><th scope="col">{kind==='loan'?'Principal repaid':'Contributions'}</th><th scope="col">{kind==='loan'?'Cumulative interest paid':'Growth'}</th></tr></thead><tbody>{rows.map(r=><tr key={r.period}><th scope="row">{r.period}</th><td>{number(r.balance)}</td><td>{number(r.contributed)}</td><td>{number(r.interest)}</td></tr>)}</tbody></table></div></Section>}<LinkButton href="/studio/visualization" secondary>Explore trading costs</LinkButton></>;
}

export function ProgramComparison(){
 const [selected,setSelected]=useState<string[]>([]);
 useEffect(()=>{const ids=new URLSearchParams(window.location.search).getAll('program');setSelected([...new Set(ids)].filter(id=>cohorts.some(c=>c.slug===id)).slice(0,3));},[]);
 function toggle(id:string){const next=selected.includes(id)?selected.filter(s=>s!==id):[...selected,id].slice(0,3);setSelected(next);const url=new URL(window.location.href);url.searchParams.delete('program');next.forEach(s=>url.searchParams.append('program',s));window.history.replaceState(null,'',url);}
 const records=cohorts.filter(c=>selected.includes(c.slug));
 return <><PageHeader eyebrow="Programs / Compare" title="Find a suitable commitment." description="Compare up to three proposed cohorts using the published preparation and curriculum. A proposed schedule is not an open admission cycle."/><fieldset className="feature-panel"><legend>Choose up to three programs</legend>{cohorts.map(c=><label className="feature-choice" key={c.slug}><input type="checkbox" checked={selected.includes(c.slug)} disabled={selected.length===3&&!selected.includes(c.slug)} onChange={()=>toggle(c.slug)}/>{c.title}</label>)}</fieldset><p role="status">{records.length} selected. This view is saved in the page address for sharing.</p>{records.length>0&&<div className="responsive-table"><table><caption>Published cohort requirements and availability</caption><thead><tr><th scope="col">Detail</th>{records.map(c=><th scope="col" key={c.slug}><a href={'/research/cohorts/'+c.slug}>{c.title}</a></th>)}</tr></thead><tbody>{['Status','Preparation','Difficulty','Duration','Workload','Deliverables','Application availability','Confirmed dates','Fees'].map(label=><tr key={label}><th scope="row">{label}</th>{records.map(c=>{const curriculum=c.curriculum??curricula[c.slug];const fields:Record<string,string>={Status:c.status,Preparation:c.background,Difficulty:c.difficulty,Duration:c.duration,Workload:curriculum?.workload??'Not published',Deliverables:c.output.join('; '),'Application availability':c.applicationStatus,'Confirmed dates':'Not published',Fees:'Not published; do not assume free or paid'};return <td key={c.slug}>{fields[label]}</td>;})}</tr>)}</tbody></table></div>}<LinkButton href="/programs" secondary>Browse programs</LinkButton></>;
}
