import { useEffect, useState } from 'react';
import { PageHeader, LinkButton } from './components';
import { glossary, practiceQuestions, scorePractice } from './content/practice';
import './features.css';
const lessonHref=(slug:string)=>'/publications/financedebriefed/'+slug;
export function Glossary(){const [query,setQuery]=useState('');const filtered=glossary.filter(g=>(g.term+' '+g.definition).toLowerCase().includes(query.trim().toLowerCase()));return <><PageHeader eyebrow="Learn / Glossary" title="Make the terms concrete." description="Definitions, examples and links to the released lessons. Use these explanations to inspect an argument and its assumptions."/><div className="feature-panel"><label>Search the glossary<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><p role="status">{filtered.length} terms</p></div><div className="glossary-grid">{filtered.map(g=><article key={g.term}><h2>{g.term}</h2><p>{g.definition}</p><p><strong>Example:</strong> {g.example}</p><a href={lessonHref(g.lesson)}>Read the related lesson</a></article>)}</div>{!filtered.length&&<button type="button" className="button secondary" onClick={()=>setQuery('')}>Clear search</button>}</>;}
type Attempt={at:string;correct:number;total:number;version:number};
function readAttempts():Attempt[]{try{const value:unknown=JSON.parse(localStorage.getItem('fm-practice-attempts')??'[]');return Array.isArray(value)?value.filter((v):v is Attempt=>Boolean(v&&typeof v==='object'&&typeof v.at==='string'&&Number.isInteger(v.correct)&&Number.isInteger(v.total)&&v.correct>=0&&v.correct<=v.total&&v.total===practiceQuestions.length&&v.version===1)).slice(-20):[];}catch{return [];}}
export function LearningPractice(){
 const [answers,setAnswers]=useState<Record<string,number>>({}),[submitted,setSubmitted]=useState(false),[attempts,setAttempts]=useState<Attempt[]>([]),[message,setMessage]=useState('');
 useEffect(()=>{setAttempts(readAttempts());},[]);const score=scorePractice(answers);
 return <><PageHeader eyebrow="Learn / Self-assessment" title="Check the reasoning." description="Eight questions across the four released explainers. Each answer includes an explanation. This practice does not award a credential."/><form onSubmit={e=>{e.preventDefault();if(score.answered!==score.total){setMessage('Answer all questions before checking your work.');return;}setSubmitted(true);const next=[...attempts,{at:new Date().toISOString(),correct:score.correct,total:score.total,version:1}].slice(-20);setAttempts(next);try{localStorage.setItem('fm-practice-attempts',JSON.stringify(next));setMessage(`${score.correct} of ${score.total} correct. Attempt saved on this browser.`);}catch{setMessage(`${score.correct} of ${score.total} correct. Browser storage is unavailable; this attempt is not saved.`);}}}>
 {practiceQuestions.map((q,i)=><fieldset className="feature-panel" key={q.id} disabled={submitted}><legend>{i+1}. {q.question}</legend>{q.options.map((option,j)=><label className="feature-choice" key={option}><input required type="radio" name={q.id} value={j} checked={answers[q.id]===j} onChange={()=>setAnswers(old=>({...old,[q.id]:j}))}/>{option}</label>)}{submitted&&<div><p><strong>{answers[q.id]===q.answer?'Correct.':'Review this answer.'}</strong> {q.explanation}</p><a href={lessonHref(q.lesson)}>Revisit the lesson</a></div>}</fieldset>)}
 {!submitted&&<button type="submit" className="button">Check answers</button>}<p role="status">{message}</p></form>{submitted&&<button type="button" className="button secondary" onClick={()=>{setAnswers({});setSubmitted(false);setMessage('');}}>Start another attempt</button>}<section className="section"><h2>Recent practice</h2><p>Up to 20 attempts are stored on this browser, separately from account-synced reading progress.</p>{attempts.length?<ol>{attempts.map((a,i)=><li key={`${a.at}-${i}`}><time dateTime={a.at}>{new Date(a.at).toLocaleString()}</time>: {a.correct}/{a.total}</li>)}</ol>:<p>No saved attempts on this browser.</p>}<button type="button" className="text-button" onClick={()=>{try{localStorage.removeItem('fm-practice-attempts');setAttempts([]);setMessage('Practice history cleared.');}catch{setMessage('Could not clear browser storage.');}}}>Clear practice history</button></section><LinkButton href="/learn/glossary" secondary>Explore the glossary</LinkButton></>;
}
