import { SaveButton } from './reading-list';
import { useEffect, useState } from 'react';
import { Arrow, CohortCard, Directory, EventCard, LinkButton, PageHeader, ProjectCard, Section, StatusBadge } from './components';
import { cohorts, events, projects, publicationPath, publications } from './content/research';
import { learningTracks } from './content/learning';
import type { Project } from './content/models';
import { ProgramTracks } from './platform-pages';


export function ResearchExplorer() {
  const items = projects.map(p => ({ slug: p.slug, title: p.name, description: p.abstract, href: '/research/projects/' + p.slug, type: 'Research', lab: p.lab, status: p.status, methods: p.methods, topics: p.keywords, date: p.updated, year: p.updated.slice(0, 4), author: p.researchers }));
  return <div className="research-explorer"><PageHeader eyebrow="Research / The open record" title="Find a question worth pursuing." description="Search project questions, methods and research fields. Every record carries its status and evidence boundary." /><Directory items={items} filters={['lab', 'methods', 'status', 'year', 'author']} label="Search research" table>{item => <div className="research-record"><ProjectCard project={projects.find(p => p.slug === item.slug)!} /><p className="record-attribution">Authors: {item.author?.length ? item.author.join(', ') : 'not recorded'} · Reproduction not verified</p></div>}</Directory><p className="fine-print">Year refers to the catalog update, not a publication date. No citation or download counts are asserted.</p></div>;
}

export function ResearchActions({ project }: { project: Project }) {
  const [message, setMessage] = useState('');
  const citation = `${project.name}. FinanceMeta project record. Updated ${project.updated}. Status: ${project.status}. ${project.researchers.length ? 'Authors: ' + project.researchers.join(', ') : 'Author attribution not established in this record.'}`;
  async function copy() { try { await navigator.clipboard.writeText(citation + ' ' + window.location.href.split('#')[0]); setMessage('Citation copied.'); } catch { setMessage('Clipboard unavailable. Select the citation text below to copy.'); } }
  return <div className="research-actions"><div className="page-actions">{project.paper ? <LinkButton href={project.paper}>Paper</LinkButton> : <span className="availability-note">Paper not released</span>}{project.repository && <LinkButton href={project.repository} secondary>GitHub</LinkButton>}<span className="availability-note">Dataset not released</span><SaveButton href={`/research/projects/${project.slug}`}/><button type="button" className="button secondary" onClick={copy}>Cite record</button></div><details className="citation-block"><summary>Readable citation</summary><p>{citation}</p></details><p role="status">{message}</p></div>;
}

export function ProgramsDirectory() {
  return <><PageHeader eyebrow="Programs / Research together" title="A question. A method. A body of work." description="Explore curricula, preparation and expected deliverables. Proposed programs remain distinct from open applications." /><div className="page-actions"><LinkButton href="/programs/compare" secondary>Compare programs</LinkButton></div><Directory items={cohorts.map(c => ({ slug: c.slug, title: c.title, description: c.description, type: 'Cohort', href: '/research/cohorts/' + c.slug, status: c.status, lab: c.lab }))} statusTabs={{ label: 'Program status', values: ['Open', 'Active', 'Completed', 'Upcoming'], defaultValue: '' }} filters={['lab']} label="Search programs" empty="No programs match this status.">{item => <CohortCard cohort={cohorts.find(c => c.slug === item.slug)!} />}</Directory><Section title="Find your participation track"><p>Research, financial ML and engineering expressions of interest are available separately from scheduled cohort admission.</p><LinkButton href="/apply">Explore application paths</LinkButton></Section><details className="program-track-details"><summary>Read the five participation tracks</summary><ProgramTracks embedded /></details></>;
}

export function LearnDirectory({ slug }: { slug?: string }) {
  const track = learningTracks.find(t => t.slug === slug);
  if (track) return <><PageHeader eyebrow="Learn / Reading pathway" title={track.title} description={track.description}><LinkButton href="/learn" secondary>All pathways</LinkButton></PageHeader><p className="evidence-note">A self-guided reading pathway using released explainers. These introductory modules are not a complete course or a credential.</p>{track.modules.map((module, index) => { const lesson = publications.find(p => p.slug === module.lesson)!; return <Section key={module.title} eyebrow={`Module ${index + 1}`} title={module.title}><div className="lesson-row"><div><p className="eyebrow">Lesson / {lesson.readMinutes} min read</p><h3><a href={publicationPath(lesson)}>{lesson.title}</a></h3><p>{lesson.abstract}</p><a href={publicationPath(lesson)} className="text-link">Read lesson <Arrow /></a></div><aside><h3>Put it into practice</h3><p>{module.exercise}</p></aside></div></Section>; })}</>;
  return <><PageHeader eyebrow="Learn / Open financial knowledge" title="Understand the system, one idea at a time." description="Start with a field, follow a module, and read the lesson. Open, self-guided pathways connect existing explainers to practical questions." /><div className="learning-tracks">{learningTracks.map((t, i) => <article key={t.slug}><span className="eyebrow">0{i + 1}</span><div><h2><a href={'/learn/' + t.slug}>{t.title} <Arrow /></a></h2><p>{t.description}</p></div><span className="fine-print">{t.modules.length} introductory {t.modules.length === 1 ? 'module' : 'modules'}</span></article>)}</div><Section title="Practice and definitions"><LinkButton href="/learn/practice" secondary>Check your understanding</LinkButton><LinkButton href="/learn/glossary" secondary>Browse the glossary</LinkButton></Section><Section title="Explore financial assumptions"><LinkButton href="/open/tools" secondary>Open finance calculators</LinkButton></Section><Section title="Build a research habit"><p>Use the research protocol worksheet to make the question, baseline and evaluation explicit before running an experiment.</p><LinkButton href="/resources/research-protocol.md" secondary download="research-protocol.md">Download worksheet</LinkButton></Section></>;
}

const marketSources = [
  { title: 'Rates', source: 'Federal Reserve', href: 'https://www.federalreserve.gov/releases/h15/', note: 'Selected interest rates; check each series’ frequency and units.', project: 'macrocast' },
  { title: 'Inflation', source: 'U.S. Bureau of Labor Statistics', href: 'https://www.bls.gov/cpi/', note: 'Consumer price indexes; compare consistent adjustment and base periods.', project: 'inflation-observatory' },
  { title: 'GDP', source: 'U.S. Bureau of Economic Analysis', href: 'https://www.bea.gov/data/gdp/gross-domestic-product', note: 'National output estimates; track revisions and release vintages.', project: 'macrocast' },
  { title: 'Employment', source: 'U.S. Bureau of Labor Statistics', href: 'https://www.bls.gov/ces/', note: 'Payroll employment statistics; distinguish levels, changes and revisions.', project: 'causal-finance' },
  { title: 'FX', source: 'Federal Reserve', href: 'https://www.federalreserve.gov/releases/h10/', note: 'Exchange-rate releases; verify the quote convention and observation date.', project: 'market-frictions' },
];
export function Markets() {
  return <><PageHeader eyebrow="Markets / Data in context" title="The observation is only the beginning." description="Understand where financial data comes from, how it changes, and which research questions it can help answer." /><nav className="section-nav" aria-label="Markets sections"><a href="#market-overview">Overview</a><a href="#macro-indicators">Macro indicators</a><a href="#economic-calendar">Economic calendar</a><a href="#research-tools">Research tools</a></nav><Section id="market-overview" title="Market overview"><div className="evidence-note"><StatusBadge>Live feed not connected</StatusBadge><p>No live or delayed prices are displayed. This source guide covers U.S. macroeconomic releases and FX references. Indices and commodities await a licensed, timestamped feed.</p></div></Section><Section id="macro-indicators" title="Macro indicators" description="Source links open the provider’s official publication. Values, freshness and release revisions must be checked there."><div className="responsive-table"><table><caption>Source guide and related Finance4All research</caption><thead><tr><th scope="col">Series</th><th scope="col">Source & interpretation</th><th scope="col">Related research</th></tr></thead><tbody>{marketSources.map(s => <tr key={s.title}><th scope="row">{s.title}</th><td data-label="Source"><a href={s.href}>{s.source} ↗</a><p>{s.note}</p></td><td data-label="Research"><a href={'/research/projects/' + s.project}>{projects.find(p => p.slug === s.project)!.name} <Arrow /></a></td></tr>)}</tbody></table></div></Section><Section id="economic-calendar" title="Economic calendar"><p>A synchronized release calendar is not connected. Consult the official release schedule before using an observation in a time-sensitive analysis.</p><div className="page-actions"><LinkButton href="https://www.bls.gov/schedule/" secondary>BLS release schedule</LinkButton><LinkButton href="https://www.bea.gov/news/schedule" secondary>BEA release schedule</LinkButton></div></Section><Section id="research-tools" title="From data to a research question"><div className="lesson-row"><div><h3>The cost of a trade</h3><p>Explore the sensitivity of a hypothetical return to turnover and transaction costs. Inputs are illustrative assumptions, not observed market prices.</p><LinkButton href="/studio/visualization">Open the interactive model</LinkButton></div><aside><p className="eyebrow">Related Finance4All research</p><h3><a href="/research/projects/market-frictions">Market Frictions</a></h3><p>How much apparent performance disappears under realistic execution assumptions?</p></aside></div></Section></>;
}

export function EventsCalendar() {
  const [month, setMonth] = useState('');
  useEffect(() => { const value = new URLSearchParams(window.location.search).get('month'); if (value && /^\d{4}-(0[1-9]|1[0-2])$/.test(value)) setMonth(value); }, []);
  function chooseMonth(value: string) { setMonth(value); const url = new URL(window.location.href); value ? url.searchParams.set('month', value) : url.searchParams.delete('month'); window.history.replaceState(null, '', url); }
  const selected = events.filter(e => !month || e.date.startsWith(month));
  const days = month ? new Date(Number(month.slice(0, 4)), Number(month.slice(5)), 0).getDate() : 0;
  const offset = month ? new Date(Number(month.slice(0, 4)), Number(month.slice(5)) - 1, 1).getDay() : 0;
  return <><PageHeader eyebrow="Events / Research in conversation" title="Put the question in the room." description="Workshops, talks, competitions and research presentations. Only confirmed events are listed; each event retains its announced timezone." /><div className="calendar-controls"><label>Calendar month<input type="month" value={month} onChange={e => chooseMonth(e.target.value)} /></label><button type="button" className="button secondary" onClick={() => chooseMonth('')}>All dates</button></div>{month && <section className="month-calendar" aria-label={`Calendar for ${month}`}><h2>{new Date(month + '-01T12:00:00').toLocaleDateString('en', { month: 'long', year: 'numeric' })}</h2><div className="calendar-grid">{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(d => <span className="eyebrow" key={d}>{d}</span>)}{Array.from({ length: offset }, (_, i) => <span key={'offset' + i} />)}{Array.from({ length: days }, (_, i) => { const date = month + '-' + String(i + 1).padStart(2, '0'); const records = selected.filter(e => e.date === date); return <div className="calendar-day" key={date}><time dateTime={date}>{i + 1}</time>{records.map(e => <a key={e.slug} href={'/events/' + e.slug} aria-label={`${e.title}, ${e.time} ${e.timezone}`}>{e.title}</a>)}</div>; })}</div><p className="fine-print">Dates use the event’s announced timezone. Event details show the full time and calendar download where available.</p></section>}<Directory items={selected.map(e => ({ slug: e.slug, title: e.title, description: `${e.date} ${e.time} ${e.timezone} · ${e.description}`, href: '/events/' + e.slug, type: e.type, status: e.status, date: e.date, mode: e.mode }))} filters={['type', 'mode']} statusTabs={{ label: 'Event period', values: ['Upcoming', 'Past'], defaultValue: 'Upcoming' }} label="Search events" empty="No confirmed upcoming sessions or verified past-event records match this view.">{item => <EventCard event={events.find(e => e.slug === item.slug)!} />}</Directory><Section title="Propose a useful discussion"><p>Suggest a question, audience and format. A submission is separate from a confirmed event.</p><LinkButton href="/join?role=Speaker%20%2F%20Mentor">Propose a session</LinkButton></Section></>;
}
